import SwiftUI

struct DisclaimerView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                // Title
                Text("Disclaimer")
                    .font(.title) // Default system font
                    .bold()
                    .foregroundColor(.blue)
                    .padding(.top, 20)

                // Disclaimer Content
                Text("""
                Last updated: [Insert Date]

                The information and services provided by Cap Call ("we," "our," or "us") are for informational and entertainment purposes only. By using the app, you agree to the following disclaimers:

                1. No Professional Advice
                - Captions generated by the App are created using automated systems, including Google Vision API and GPT-4.
                - These captions are not intended to provide professional advice, recommendations, or guarantees of accuracy.

                2. Accuracy and Limitations
                - While we strive to provide accurate and high-quality captions, the output may not always be appropriate, relevant, or error-free.
                - The App relies on third-party services, such as Google Vision API and GPT-4, which have limitations in detecting inappropriate or offensive content. Users are responsible for reviewing and verifying all outputs before use.

                3. User Responsibility
                - You are solely responsible for the content you upload, the captions generated, and how you use them.
                - By uploading images, you confirm that you have the necessary rights and consents from all identifiable individuals featured.
                - We are not liable for any consequences, damages, or claims arising from the use of the App, including inappropriate captions or misuse of generated content.

                4. Third-Party Services
                - The App integrates with third-party services, including Google Vision API and GPT-4. We do not control these services and are not responsible for their performance, accuracy, or compliance with your intended use.

                5. Limitation of Liability
                - To the fullest extent permitted by law, we are not liable for any direct, indirect, incidental, or consequential damages resulting from your use of the App.

                6. Changes to This Disclaimer
                - We may update this Disclaimer from time to time. Changes will be effective upon posting in the App. Continued use of the App after updates signifies your acceptance of the revised Disclaimer.

                7. Contact Us
                If you have any questions about this Disclaimer, please contact us at [Insert Email Address].
                """)
                .font(.body) // Default system font for readability
                .foregroundColor(.primary)
                .multilineTextAlignment(.leading)
                .padding(.bottom, 20)
            }
            .padding()
        }
        .navigationTitle("Disclaimer")
    }
}

