import SwiftUI

struct TermsOfServiceView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                // Title
                Text("Terms of Service")
                    .font(.title) // Default system font
                    .bold()
                    .foregroundColor(.blue)
                    .padding(.top, 20)

                // Full Terms of Service
                Text("""
                Last updated: [Insert Date]

                Welcome to Cap Call ("we," "our," or "us"). These Terms of Service ("Terms") govern your access to and use of the Cap Call mobile application ("App") and associated services ("Services"). By downloading, accessing, or using the App, you agree to comply with these Terms.

                If you do not agree to these Terms, do not use the App or Services.

                1. Eligibility
                You must be at least 13 years old to use the App. By using the App, you represent and warrant that you meet this requirement.

                2. Account Registration
                - You must create an account to access certain features.
                - You agree to provide accurate, complete, and up-to-date information during registration.
                - You are responsible for maintaining the confidentiality of your login credentials and agree to notify us immediately if you suspect unauthorized use.
                - Offensive, hateful, or impersonating usernames are strictly prohibited.

                3. Subscription and Payments
                - Access to certain features requires a subscription. All payments are processed via Apple's In-App Purchase (IAP) system.
                - Subscriptions automatically renew unless canceled at least 24 hours before the end of the billing cycle.
                - All sales are final, and no refunds, free trials, or discounts are offered.
                - Users can cancel their subscriptions anytime through Apple's standard practices.

                4. User Content and Accountability
                - You are solely responsible for all images and content you upload to the App and any captions generated by the App.
                - By uploading images to the App, you confirm that you have obtained all necessary permissions and consents from any identifiable individuals featured in the images. This includes ensuring compliance with applicable privacy laws and regulations.
                - You agree not to upload content that violates laws, infringes upon third-party rights, or is deemed inappropriate or offensive.
                - Although the App utilizes Google Vision API's SafeSearch and other automated filtering systems, we do not guarantee that all inappropriate content will be detected or blocked. You acknowledge that the accuracy of such systems is limited, and you are responsible for reviewing all outputs before use.
                - You agree to indemnify and hold us harmless against any claims, damages, or liabilities arising from your use of the App, including the misuse of captions, images, or lack of necessary consents.

                5. Prohibited Activities
                You agree not to:
                - Use the App for illegal purposes.
                - Upload offensive, obscene, or infringing content.
                - Reverse-engineer or tamper with the App's functionality.
                - Attempt to bypass payment systems or subscription requirements.

                6. Data Retention and Account Deletion
                - Uploaded images and personal content are deleted immediately upon account deletion.
                - Minimal data, such as payment records and compliance logs, may be retained securely for up to 180 days, per Firebase’s data retention practices.
                - To fully delete your account data, you must email us at [Insert Email Address], and we will manually delete your account from Firebase.

                7. Third-Party Services
                - Our App relies on third-party services, including Google Vision API (with SafeSearch) and OpenAI's GPT-4, for processing.
                - By using the App, you agree to the terms and data practices of these third-party services.

                8. Disclaimer of Warranties
                - The App is provided "as is" without warranties of any kind.
                - We do not guarantee the accuracy of captions or uninterrupted availability of the App.

                9. Limitation of Liability
                To the fullest extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the App.

                10. Dispute Resolution
                Any disputes arising out of or relating to these Terms shall be resolved through binding arbitration in the state of Texas, unless prohibited by law.

                11. Modification of Services
                We reserve the right to modify, suspend, or discontinue any features or services at any time without prior notice.

                12. Changes to These Terms
                We may update these Terms from time to time. Changes will be effective upon posting. Continued use of the App after changes are posted constitutes your acceptance of the revised Terms.

                13. Contact Information
                If you have any questions about these Terms, contact us at [Insert Email Address].
                """)
                .font(.body) // Default system font for readability
                .foregroundColor(.primary)
                .multilineTextAlignment(.leading)
                .padding(.bottom, 20)
            }
            .padding()
        }
        .navigationTitle("Terms of Service")
    }
}

